// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnifiedRewards.Infrastructure.Persistence;

#nullable disable

namespace UnifiedRewards.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608085428_AddBenefitsModule")]
    partial class AddBenefitsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("UnifiedRewards.Domain.Benefits.BenefitEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BenefitPlanId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CoverageStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenefitPlanId");

                    b.HasIndex("EmployeeId", "BenefitPlanId");

                    b.ToTable("BenefitEnrollments", (string)null);
                });

            modelBuilder.Entity("UnifiedRewards.Domain.Benefits.BenefitPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BenefitPlans", (string)null);
                });

            modelBuilder.Entity("UnifiedRewards.Domain.UserManagement.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UnifiedRewards.Domain.UserManagement.Employee", b =>
                {
                    b.HasBaseType("UnifiedRewards.Domain.UserManagement.User");

                    b.Property<DateOnly>("DateOfJoining")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("UnifiedRewards.Domain.UserManagement.FinanceUser", b =>
                {
                    b.HasBaseType("UnifiedRewards.Domain.UserManagement.User");

                    b.HasDiscriminator().HasValue("FinanceUser");
                });

            modelBuilder.Entity("UnifiedRewards.Domain.UserManagement.HrAdmin", b =>
                {
                    b.HasBaseType("UnifiedRewards.Domain.UserManagement.User");

                    b.HasDiscriminator().HasValue("HrAdmin");
                });

            modelBuilder.Entity("UnifiedRewards.Domain.UserManagement.Manager", b =>
                {
                    b.HasBaseType("UnifiedRewards.Domain.UserManagement.Employee");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("UnifiedRewards.Domain.Benefits.BenefitEnrollment", b =>
                {
                    b.HasOne("UnifiedRewards.Domain.Benefits.BenefitPlan", "BenefitPlan")
                        .WithMany("Enrollments")
                        .HasForeignKey("BenefitPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BenefitPlan");
                });

            modelBuilder.Entity("UnifiedRewards.Domain.Benefits.BenefitPlan", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
